# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6:
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*/
      - test-2.7:
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*/
      - pypi:
          requires:
            - test-3.6
            - test-2.7
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  test-3.6:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.5
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements/test.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: activate virtualenv and install dependencies.
          command: |
            test -d venv || virtualenv -p python3 ./venv
            . venv/bin/activate
            pip install -r requirements/test.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/test.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make run-tests
            bash <(curl -s https://codecov.io/bash)

  # Based on answer https://discuss.circleci.com/t/run-tests-on-multiple-versions-of-python/15462
  test-2.7:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo27

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-27-dependencies-{{ checksum "requirements/test.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-27-dependencies-

      - run:
          name: activate virtualenv and install dependencies.
          command: |
            test -d venv || virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements/test.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-27-dependencies-{{ checksum "requirements/test.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make run-tests

  pypi:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: Init .pypirc
          command: |
            echo $'[distutils]\nindex-servers = pypi\n[pypi]' > ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Prepare venv for distribution
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install twine
      - run:
          name: Create package
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: Check package
          command: |
            source venv/bin/activate
            twine check dist/*
      - run:
          name: Upload to pypi
          command: |
            source venv/bin/activate
            twine upload dist/*
