name: Tutor Integration Tests
on: [pull_request]

jobs:
  integration-test:
    name: Tutor Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tutor_version: ["<17.0.0", "<18.0.0", "<19.0.0"]
    steps:
      - uses: actions/checkout@v4
        with:
          path: eox-audit-model
      - uses: eduNEXT/integration-test-in-tutor@main
        with:
          tutor_version: ${{ matrix.tutor_version }}
          app_name: "eox-audit-model"
          shell_file_to_run: "eox_audit_model/tests/tutor/integration.sh"
